export const ACTION_TYPE ={
    SET_USER: "SET_USER", 
    LOGOUT: "LOGOUT",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    ADD_BUSKET_DATA: "ADD_BUSKET_DATA",
    REMOVE_BUSKET_DATA: "REMOVE_BUSKET_DATA",
    CLEAR_BUSKET_DATA: "CLEAR_BUSKET_DATA",
}

