export * from "./Main-Page/main-page";
export * from "./Login-Page/login-page";
export * from "./Product-Page/product-page";
export * from "./Busket-Page/busket";
export * from "./Register-Page/register-page"
export * from "./Admin-panel"
export * from "./Error-page"
export * from "./Payment-page/Payment-Page"
export * from "./Report-Page/report-page"